services:
  app:
    image: ghcr.io/haejin315/mywebchat-app:latest
    container_name: mywebchat-app
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - PORT=8080

  nginx:
    image: ghcr.io/haejin315/mywebchat-nginx:latest
    container_name: mywebchat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
